import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#2b4870',
        'inverse-primary': '#705093',
        'on-secondary': '#103158',
        background: '#171024',
        'on-secondary-fixed': '#001c3b',
        'surface-container-high': '#2e263c',
        'primary-container': '#240046',
        'risk-verified': '#1D9E75',
        'primary-fixed': '#efdbff',
        'on-surface': '#eaddfa',
        'on-tertiary-fixed': '#001f25',
        outline: '#968e9a',
        'on-background': '#eaddfa',
        'on-secondary-container': '#9ab6e5',
        'tertiary-fixed-dim': '#00daf5',
        'risk-spam-bg': '#2F2110',
        'secondary-fixed-dim': '#acc8f7',
        'on-tertiary': '#00363e',
        'primary-fixed-dim': '#dbb8ff',
        'on-error-container': '#ffdad6',
        'on-primary': '#402061',
        'inverse-on-surface': '#342d42',
        'tertiary-container': '#001a1f',
        'risk-fraud-bg': '#2E151B',
        'surface-deck-white': '#FFFFFF',
        'surface-container': '#231c31',
        'secondary-fixed': '#d5e3ff',
        'surface-container-lowest': '#110a1e',
        'risk-fraud': '#E24B4A',
        'surface-container-elevated': '#2E0A52',
        'risk-nodata': '#B4B2A9',
        'surface-dim': '#171024',
        'on-primary-fixed-variant': '#57387a',
        'surface-tint': '#dbb8ff',
        'on-error': '#690005',
        'risk-spam': '#EF9F27',
        'on-tertiary-container': '#008da0',
        'risk-nodata-bg': '#242322',
        'surface-container-low': '#1f182c',
        primary: '#dbb8ff',
        'risk-verified-bg': '#0E2820',
        'surface-bright': '#3d354c',
        tertiary: '#00daf5',
        'tertiary-fixed': '#a1efff',
        'on-primary-fixed': '#2a064b',
        'outline-variant': '#4b444f',
        'on-tertiary-fixed-variant': '#004e59',
        'on-surface-variant': '#cdc3d0',
        'error-container': '#93000a',
        'surface-container-dark': '#1A0033',
        secondary: '#acc8f7',
        'surface-container-highest': '#393147',
        error: '#ffb4ab',
        'on-primary-container': '#9371b8',
        'secondary-container': '#2b4870',
        'inverse-surface': '#eaddfa',
        surface: '#171024',
        'surface-deck-muted': '#F1F1F1',
        'surface-variant': '#393147',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit-sm': '0.75rem',
        'unit-lg': '1.5rem',
        'max-width-content': '1440px',
        'unit-2xl': '3rem',
        'gutter-desktop': '1.5rem',
        'unit-xs': '0.5rem',
        'unit-3xl': '4rem',
        'unit-xl': '2rem',
        'unit-md': '1rem',
        'unit-2xs': '0.25rem',
        'margin-desktop': '3rem',
        18: '4.5rem',
      },
      scale: {
        98: '0.98',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-hero': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '300' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'code-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '500' }],
        'title-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
